<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('codigos_sat', function (Blueprint $table) {
            $table->id();
            $table->string('codigo_agrupador', 20)->comment('Código agrupador de cuentas del SAT');
            $table->integer('nivel')->comment('Nivel de la cuenta (1, 2, etc.)');
            $table->string('nombre_cuenta', 500)->comment('Nombre de la cuenta y/o subcuenta');
            $table->timestamps();
            
            $table->index('codigo_agrupador');
            $table->index('nivel');
        });

        $registros = [
            // ==================== ACTIVO (100) ====================
            ['codigo_agrupador' => '100', 'nivel' => 1, 'nombre_cuenta' => 'Activo'],
            ['codigo_agrupador' => '100.01', 'nivel' => 1, 'nombre_cuenta' => 'Activo a corto plazo'],
            ['codigo_agrupador' => '101', 'nivel' => 1, 'nombre_cuenta' => 'Caja'],
            ['codigo_agrupador' => '101.01', 'nivel' => 2, 'nombre_cuenta' => 'Caja y efectivo'],
            ['codigo_agrupador' => '102', 'nivel' => 1, 'nombre_cuenta' => 'Bancos'],
            ['codigo_agrupador' => '102.01', 'nivel' => 2, 'nombre_cuenta' => 'Bancos nacionales'],
            ['codigo_agrupador' => '102.02', 'nivel' => 2, 'nombre_cuenta' => 'Bancos extranjeros'],
            ['codigo_agrupador' => '103', 'nivel' => 1, 'nombre_cuenta' => 'Inversiones'],
            ['codigo_agrupador' => '103.01', 'nivel' => 2, 'nombre_cuenta' => 'Inversiones temporales'],
            ['codigo_agrupador' => '103.02', 'nivel' => 2, 'nombre_cuenta' => 'Inversiones en fideicomisos'],
            ['codigo_agrupador' => '103.03', 'nivel' => 2, 'nombre_cuenta' => 'Otras inversiones'],
            ['codigo_agrupador' => '104', 'nivel' => 1, 'nombre_cuenta' => 'Otros instrumentos financieros'],
            ['codigo_agrupador' => '104.01', 'nivel' => 2, 'nombre_cuenta' => 'Otros instrumentos financieros'],
            ['codigo_agrupador' => '105', 'nivel' => 1, 'nombre_cuenta' => 'Clientes'],
            ['codigo_agrupador' => '105.01', 'nivel' => 2, 'nombre_cuenta' => 'Clientes nacionales'],
            ['codigo_agrupador' => '105.02', 'nivel' => 2, 'nombre_cuenta' => 'Clientes extranjeros'],
            ['codigo_agrupador' => '105.03', 'nivel' => 2, 'nombre_cuenta' => 'Clientes nacionales parte relacionada'],
            ['codigo_agrupador' => '105.04', 'nivel' => 2, 'nombre_cuenta' => 'Clientes extranjeros parte relacionada'],
            ['codigo_agrupador' => '106', 'nivel' => 1, 'nombre_cuenta' => 'Cuentas y documentos por cobrar a corto plazo'],
            ['codigo_agrupador' => '106.01', 'nivel' => 2, 'nombre_cuenta' => 'Cuentas y documentos por cobrar a corto plazo nacional'],
            ['codigo_agrupador' => '106.02', 'nivel' => 2, 'nombre_cuenta' => 'Cuentas y documentos por cobrar a corto plazo extranjero'],
            ['codigo_agrupador' => '106.03', 'nivel' => 2, 'nombre_cuenta' => 'Cuentas y documentos por cobrar a corto plazo nacional parte relacionada'],
            ['codigo_agrupador' => '106.04', 'nivel' => 2, 'nombre_cuenta' => 'Cuentas y documentos por cobrar a corto plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '106.05', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por cobrar a corto plazo nacional'],
            ['codigo_agrupador' => '106.06', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por cobrar a corto plazo extranjero'],
            ['codigo_agrupador' => '106.07', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por cobrar a corto plazo nacional parte relacionada'],
            ['codigo_agrupador' => '106.08', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por cobrar a corto plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '106.09', 'nivel' => 2, 'nombre_cuenta' => 'Otras cuentas y documentos por cobrar a corto plazo'],
            ['codigo_agrupador' => '106.10', 'nivel' => 2, 'nombre_cuenta' => 'Otras cuentas y documentos por cobrar a corto plazo parte relacionada'],
            ['codigo_agrupador' => '107', 'nivel' => 1, 'nombre_cuenta' => 'Deudores diversos'],
            ['codigo_agrupador' => '107.01', 'nivel' => 2, 'nombre_cuenta' => 'Funcionarios y empleados'],
            ['codigo_agrupador' => '107.02', 'nivel' => 2, 'nombre_cuenta' => 'Socios y accionistas'],
            ['codigo_agrupador' => '107.03', 'nivel' => 2, 'nombre_cuenta' => 'Partes relacionadas nacionales'],
            ['codigo_agrupador' => '107.04', 'nivel' => 2, 'nombre_cuenta' => 'Partes relacionadas extranjeros'],
            ['codigo_agrupador' => '107.05', 'nivel' => 2, 'nombre_cuenta' => 'Otros deudores diversos'],
            ['codigo_agrupador' => '108', 'nivel' => 1, 'nombre_cuenta' => 'Estimación de cuentas incobrables'],
            ['codigo_agrupador' => '108.01', 'nivel' => 2, 'nombre_cuenta' => 'Estimación de cuentas incobrables nacional'],
            ['codigo_agrupador' => '108.02', 'nivel' => 2, 'nombre_cuenta' => 'Estimación de cuentas incobrables extranjero'],
            ['codigo_agrupador' => '108.03', 'nivel' => 2, 'nombre_cuenta' => 'Estimación de cuentas incobrables nacional parte relacionada'],
            ['codigo_agrupador' => '108.04', 'nivel' => 2, 'nombre_cuenta' => 'Estimación de cuentas incobrables extranjero parte relacionada'],
            ['codigo_agrupador' => '109', 'nivel' => 1, 'nombre_cuenta' => 'Pagos anticipados'],
            ['codigo_agrupador' => '109.01', 'nivel' => 2, 'nombre_cuenta' => 'Seguros y fianzas pagados por anticipado nacional'],
            ['codigo_agrupador' => '109.02', 'nivel' => 2, 'nombre_cuenta' => 'Seguros y fianzas pagados por anticipado extranjero'],
            ['codigo_agrupador' => '109.03', 'nivel' => 2, 'nombre_cuenta' => 'Seguros y fianzas pagados por anticipado nacional parte relacionada'],
            ['codigo_agrupador' => '109.04', 'nivel' => 2, 'nombre_cuenta' => 'Seguros y fianzas pagados por anticipado extranjero parte relacionada'],
            ['codigo_agrupador' => '109.05', 'nivel' => 2, 'nombre_cuenta' => 'Rentas pagados por anticipado nacional'],
            ['codigo_agrupador' => '109.06', 'nivel' => 2, 'nombre_cuenta' => 'Rentas pagados por anticipado extranjero'],
            ['codigo_agrupador' => '109.07', 'nivel' => 2, 'nombre_cuenta' => 'Rentas pagados por anticipado nacional parte relacionada'],
            ['codigo_agrupador' => '109.08', 'nivel' => 2, 'nombre_cuenta' => 'Rentas pagados por anticipado extranjero parte relacionada'],
            ['codigo_agrupador' => '109.09', 'nivel' => 2, 'nombre_cuenta' => 'Intereses pagados por anticipado nacional'],
            ['codigo_agrupador' => '109.10', 'nivel' => 2, 'nombre_cuenta' => 'Intereses pagados por anticipado extranjero'],
            ['codigo_agrupador' => '109.11', 'nivel' => 2, 'nombre_cuenta' => 'Intereses pagados por anticipado nacional parte relacionada'],
            ['codigo_agrupador' => '109.12', 'nivel' => 2, 'nombre_cuenta' => 'Intereses pagados por anticipado extranjero parte relacionada'],
            ['codigo_agrupador' => '109.13', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero pagados por anticipado nacional'],
            ['codigo_agrupador' => '109.14', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero pagados por anticipado extranjero'],
            ['codigo_agrupador' => '109.15', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero pagados por anticipado nacional parte relacionada'],
            ['codigo_agrupador' => '109.16', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero pagados por anticipado extranjero parte relacionada'],
            ['codigo_agrupador' => '109.17', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero pagados por anticipado nacional'],
            ['codigo_agrupador' => '109.18', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero pagados por anticipado extranjero'],
            ['codigo_agrupador' => '109.19', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero pagados por anticipado nacional parte relacionada'],
            ['codigo_agrupador' => '109.20', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero pagados por anticipado extranjero parte relacionada'],
            ['codigo_agrupador' => '109.21', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro de pagos anticipados'],
            ['codigo_agrupador' => '109.22', 'nivel' => 2, 'nombre_cuenta' => 'Derechos fiduciarios'],
            ['codigo_agrupador' => '109.23', 'nivel' => 2, 'nombre_cuenta' => 'Otros pagos anticipados'],
            ['codigo_agrupador' => '110', 'nivel' => 1, 'nombre_cuenta' => 'Subsidio al empleo por aplicar'],
            ['codigo_agrupador' => '110.01', 'nivel' => 2, 'nombre_cuenta' => 'Subsidio al empleo por aplicar'],
            ['codigo_agrupador' => '111', 'nivel' => 1, 'nombre_cuenta' => 'Crédito al diesel por acreditar'],
            ['codigo_agrupador' => '111.01', 'nivel' => 2, 'nombre_cuenta' => 'Crédito al diesel por acreditar'],
            ['codigo_agrupador' => '112', 'nivel' => 1, 'nombre_cuenta' => 'Otros estímulos'],
            ['codigo_agrupador' => '112.01', 'nivel' => 2, 'nombre_cuenta' => 'Otros estímulos'],
            ['codigo_agrupador' => '113', 'nivel' => 1, 'nombre_cuenta' => 'Impuestos a favor'],
            ['codigo_agrupador' => '113.01', 'nivel' => 2, 'nombre_cuenta' => 'IVA a favor'],
            ['codigo_agrupador' => '113.02', 'nivel' => 2, 'nombre_cuenta' => 'ISR a favor'],
            ['codigo_agrupador' => '113.03', 'nivel' => 2, 'nombre_cuenta' => 'IETU a favor'],
            ['codigo_agrupador' => '113.04', 'nivel' => 2, 'nombre_cuenta' => 'IDE a favor'],
            ['codigo_agrupador' => '113.05', 'nivel' => 2, 'nombre_cuenta' => 'IA a favor'],
            ['codigo_agrupador' => '113.06', 'nivel' => 2, 'nombre_cuenta' => 'Subsidio al empleo'],
            ['codigo_agrupador' => '113.07', 'nivel' => 2, 'nombre_cuenta' => 'Pago de lo indebido'],
            ['codigo_agrupador' => '113.08', 'nivel' => 2, 'nombre_cuenta' => 'Otros impuestos a favor'],
            ['codigo_agrupador' => '114', 'nivel' => 1, 'nombre_cuenta' => 'Pagos provisionales'],
            ['codigo_agrupador' => '114.01', 'nivel' => 2, 'nombre_cuenta' => 'Pagos provisionales de ISR'],
            ['codigo_agrupador' => '115', 'nivel' => 1, 'nombre_cuenta' => 'Inventario'],
            ['codigo_agrupador' => '115.01', 'nivel' => 2, 'nombre_cuenta' => 'Inventario'],
            ['codigo_agrupador' => '115.02', 'nivel' => 2, 'nombre_cuenta' => 'Materia prima y materiales'],
            ['codigo_agrupador' => '115.03', 'nivel' => 2, 'nombre_cuenta' => 'Producción en proceso'],
            ['codigo_agrupador' => '115.04', 'nivel' => 2, 'nombre_cuenta' => 'Productos terminados'],
            ['codigo_agrupador' => '115.05', 'nivel' => 2, 'nombre_cuenta' => 'Mercancías en tránsito'],
            ['codigo_agrupador' => '115.06', 'nivel' => 2, 'nombre_cuenta' => 'Mercancías en poder de terceros'],
            ['codigo_agrupador' => '115.07', 'nivel' => 2, 'nombre_cuenta' => 'Otros'],
            ['codigo_agrupador' => '116', 'nivel' => 1, 'nombre_cuenta' => 'Estimación de inventarios obsoletos y de lento movimiento'],
            ['codigo_agrupador' => '116.01', 'nivel' => 2, 'nombre_cuenta' => 'Estimación de inventarios obsoletos y de lento movimiento'],
            ['codigo_agrupador' => '117', 'nivel' => 1, 'nombre_cuenta' => 'Obras en proceso de inmuebles'],
            ['codigo_agrupador' => '117.01', 'nivel' => 2, 'nombre_cuenta' => 'Obras en proceso de inmuebles'],
            ['codigo_agrupador' => '118', 'nivel' => 1, 'nombre_cuenta' => 'Impuestos acreditables pagados'],
            ['codigo_agrupador' => '118.01', 'nivel' => 2, 'nombre_cuenta' => 'IVA acreditable pagado'],
            ['codigo_agrupador' => '118.02', 'nivel' => 2, 'nombre_cuenta' => 'IVA acreditable de importación pagado'],
            ['codigo_agrupador' => '118.03', 'nivel' => 2, 'nombre_cuenta' => 'IEPS acreditable pagado'],
            ['codigo_agrupador' => '118.04', 'nivel' => 2, 'nombre_cuenta' => 'IEPS pagado en importación'],
            ['codigo_agrupador' => '119', 'nivel' => 1, 'nombre_cuenta' => 'Impuestos acreditables por pagar'],
            ['codigo_agrupador' => '119.01', 'nivel' => 2, 'nombre_cuenta' => 'IVA pendiente de pago'],
            ['codigo_agrupador' => '119.02', 'nivel' => 2, 'nombre_cuenta' => 'IVA de importación pendiente de pago'],
            ['codigo_agrupador' => '119.03', 'nivel' => 2, 'nombre_cuenta' => 'IEPS pendiente de pago'],
            ['codigo_agrupador' => '119.04', 'nivel' => 2, 'nombre_cuenta' => 'IEPS pendiente de pago en importación'],
            ['codigo_agrupador' => '120', 'nivel' => 1, 'nombre_cuenta' => 'Anticipo a proveedores'],
            ['codigo_agrupador' => '120.01', 'nivel' => 2, 'nombre_cuenta' => 'Anticipo a proveedores nacional'],
            ['codigo_agrupador' => '120.02', 'nivel' => 2, 'nombre_cuenta' => 'Anticipo a proveedores extranjero'],
            ['codigo_agrupador' => '120.03', 'nivel' => 2, 'nombre_cuenta' => 'Anticipo a proveedores nacional parte relacionada'],
            ['codigo_agrupador' => '120.04', 'nivel' => 2, 'nombre_cuenta' => 'Anticipo a proveedores extranjero parte relacionada'],
            ['codigo_agrupador' => '121', 'nivel' => 1, 'nombre_cuenta' => 'Otros activos a corto plazo'],
            ['codigo_agrupador' => '121.01', 'nivel' => 2, 'nombre_cuenta' => 'Otros activos a corto plazo'],
            ['codigo_agrupador' => '100.02', 'nivel' => 1, 'nombre_cuenta' => 'Activo a largo plazo'],
            ['codigo_agrupador' => '151', 'nivel' => 1, 'nombre_cuenta' => 'Terrenos'],
            ['codigo_agrupador' => '151.01', 'nivel' => 2, 'nombre_cuenta' => 'Terrenos'],
            ['codigo_agrupador' => '152', 'nivel' => 1, 'nombre_cuenta' => 'Edificios'],
            ['codigo_agrupador' => '152.01', 'nivel' => 2, 'nombre_cuenta' => 'Edificios'],
            ['codigo_agrupador' => '153', 'nivel' => 1, 'nombre_cuenta' => 'Maquinaria y equipo'],
            ['codigo_agrupador' => '153.01', 'nivel' => 2, 'nombre_cuenta' => 'Maquinaria y equipo'],
            ['codigo_agrupador' => '154', 'nivel' => 1, 'nombre_cuenta' => 'Automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques'],
            ['codigo_agrupador' => '154.01', 'nivel' => 2, 'nombre_cuenta' => 'Automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques'],
            ['codigo_agrupador' => '155', 'nivel' => 1, 'nombre_cuenta' => 'Mobiliario y equipo de oficina'],
            ['codigo_agrupador' => '155.01', 'nivel' => 2, 'nombre_cuenta' => 'Mobiliario y equipo de oficina'],
            ['codigo_agrupador' => '156', 'nivel' => 1, 'nombre_cuenta' => 'Equipo de cómputo'],
            ['codigo_agrupador' => '156.01', 'nivel' => 2, 'nombre_cuenta' => 'Equipo de cómputo'],
            ['codigo_agrupador' => '157', 'nivel' => 1, 'nombre_cuenta' => 'Equipo de comunicación'],
            ['codigo_agrupador' => '157.01', 'nivel' => 2, 'nombre_cuenta' => 'Equipo de comunicación'],
            ['codigo_agrupador' => '158', 'nivel' => 1, 'nombre_cuenta' => 'Activos biológicos, vegetales y semovientes'],
            ['codigo_agrupador' => '158.01', 'nivel' => 2, 'nombre_cuenta' => 'Activos biológicos, vegetales y semovientes'],
            ['codigo_agrupador' => '159', 'nivel' => 1, 'nombre_cuenta' => 'Obras en proceso de activos fijos'],
            ['codigo_agrupador' => '159.01', 'nivel' => 2, 'nombre_cuenta' => 'Obras en proceso de activos fijos'],
            ['codigo_agrupador' => '160', 'nivel' => 1, 'nombre_cuenta' => 'Otros activos fijos'],
            ['codigo_agrupador' => '160.01', 'nivel' => 2, 'nombre_cuenta' => 'Otros activos fijos'],
            ['codigo_agrupador' => '161', 'nivel' => 1, 'nombre_cuenta' => 'Ferrocarriles'],
            ['codigo_agrupador' => '161.01', 'nivel' => 2, 'nombre_cuenta' => 'Ferrocarriles'],
            ['codigo_agrupador' => '162', 'nivel' => 1, 'nombre_cuenta' => 'Embarcaciones'],
            ['codigo_agrupador' => '162.01', 'nivel' => 2, 'nombre_cuenta' => 'Embarcaciones'],
            ['codigo_agrupador' => '163', 'nivel' => 1, 'nombre_cuenta' => 'Aviones'],
            ['codigo_agrupador' => '163.01', 'nivel' => 2, 'nombre_cuenta' => 'Aviones'],
            ['codigo_agrupador' => '164', 'nivel' => 1, 'nombre_cuenta' => 'Troqueles, moldes, matrices y herramental'],
            ['codigo_agrupador' => '164.01', 'nivel' => 2, 'nombre_cuenta' => 'Troqueles, moldes, matrices y herramental'],
            ['codigo_agrupador' => '165', 'nivel' => 1, 'nombre_cuenta' => 'Equipo de comunicaciones telefónicas'],
            ['codigo_agrupador' => '165.01', 'nivel' => 2, 'nombre_cuenta' => 'Equipo de comunicaciones telefónicas'],
            ['codigo_agrupador' => '166', 'nivel' => 1, 'nombre_cuenta' => 'Equipo de comunicación satelital'],
            ['codigo_agrupador' => '166.01', 'nivel' => 2, 'nombre_cuenta' => 'Equipo de comunicación satelital'],
            ['codigo_agrupador' => '167', 'nivel' => 1, 'nombre_cuenta' => 'Equipo de adaptaciones para personas con capacidades diferentes'],
            ['codigo_agrupador' => '167.01', 'nivel' => 2, 'nombre_cuenta' => 'Equipo de adaptaciones para personas con capacidades diferentes'],
            ['codigo_agrupador' => '168', 'nivel' => 1, 'nombre_cuenta' => 'Maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente'],
            ['codigo_agrupador' => '168.01', 'nivel' => 2, 'nombre_cuenta' => 'Maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente'],
            ['codigo_agrupador' => '169', 'nivel' => 1, 'nombre_cuenta' => 'Otra maquinaria y equipo'],
            ['codigo_agrupador' => '169.01', 'nivel' => 2, 'nombre_cuenta' => 'Otra maquinaria y equipo'],
            ['codigo_agrupador' => '170', 'nivel' => 1, 'nombre_cuenta' => 'Adaptaciones y mejoras'],
            ['codigo_agrupador' => '170.01', 'nivel' => 2, 'nombre_cuenta' => 'Adaptaciones y mejoras'],
            ['codigo_agrupador' => '171', 'nivel' => 1, 'nombre_cuenta' => 'Depreciación acumulada de activos fijos'],
            ['codigo_agrupador' => '171.01', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de edificios'],
            ['codigo_agrupador' => '171.02', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de maquinaria y equipo'],
            ['codigo_agrupador' => '171.03', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques'],
            ['codigo_agrupador' => '171.04', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de mobiliario y equipo de oficina'],
            ['codigo_agrupador' => '171.05', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de equipo de cómputo'],
            ['codigo_agrupador' => '171.06', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de equipo de comunicación'],
            ['codigo_agrupador' => '171.07', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de activos biológicos, vegetales y semovientes'],
            ['codigo_agrupador' => '171.08', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de otros activos fijos'],
            ['codigo_agrupador' => '171.09', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de ferrocarriles'],
            ['codigo_agrupador' => '171.10', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de embarcaciones'],
            ['codigo_agrupador' => '171.11', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de aviones'],
            ['codigo_agrupador' => '171.12', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de troqueles, moldes, matrices y herramental'],
            ['codigo_agrupador' => '171.13', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de equipo de comunicaciones telefónicas'],
            ['codigo_agrupador' => '171.14', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de equipo de comunicación satelital'],
            ['codigo_agrupador' => '171.15', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de equipo de adaptaciones para personas con capacidades diferentes'],
            ['codigo_agrupador' => '171.16', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente'],
            ['codigo_agrupador' => '171.17', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de adaptaciones y mejoras'],
            ['codigo_agrupador' => '171.18', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación acumulada de otra maquinaria y equipo'],
            ['codigo_agrupador' => '172', 'nivel' => 1, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de activos fijos'],
            ['codigo_agrupador' => '172.01', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de edificios'],
            ['codigo_agrupador' => '172.02', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de maquinaria y equipo'],
            ['codigo_agrupador' => '172.03', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques'],
            ['codigo_agrupador' => '172.04', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de mobiliario y equipo de oficina'],
            ['codigo_agrupador' => '172.05', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de equipo de cómputo'],
            ['codigo_agrupador' => '172.06', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de equipo de comunicación'],
            ['codigo_agrupador' => '172.07', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de activos biológicos, vegetales y semovientes'],
            ['codigo_agrupador' => '172.08', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de otros activos fijos'],
            ['codigo_agrupador' => '172.09', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de ferrocarriles'],
            ['codigo_agrupador' => '172.10', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de embarcaciones'],
            ['codigo_agrupador' => '172.11', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de aviones'],
            ['codigo_agrupador' => '172.12', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de troqueles, moldes, matrices y herramental'],
            ['codigo_agrupador' => '172.13', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de equipo de comunicaciones telefónicas'],
            ['codigo_agrupador' => '172.14', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de equipo de comunicación satelital'],
            ['codigo_agrupador' => '172.15', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de equipo de adaptaciones para personas con capacidades diferentes'],
            ['codigo_agrupador' => '172.16', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente'],
            ['codigo_agrupador' => '172.17', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de adaptaciones y mejoras'],
            ['codigo_agrupador' => '172.18', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida por deterioro acumulado de otra maquinaria y equipo'],
            ['codigo_agrupador' => '173', 'nivel' => 1, 'nombre_cuenta' => 'Gastos diferidos'],
            ['codigo_agrupador' => '173.01', 'nivel' => 2, 'nombre_cuenta' => 'Gastos diferidos'],
            ['codigo_agrupador' => '174', 'nivel' => 1, 'nombre_cuenta' => 'Gastos pre operativos'],
            ['codigo_agrupador' => '174.01', 'nivel' => 2, 'nombre_cuenta' => 'Gastos pre operativos'],
            ['codigo_agrupador' => '175', 'nivel' => 1, 'nombre_cuenta' => 'Regalías, asistencia técnica y otros gastos diferidos'],
            ['codigo_agrupador' => '175.01', 'nivel' => 2, 'nombre_cuenta' => 'Regalías, asistencia técnica y otros gastos diferidos'],
            ['codigo_agrupador' => '176', 'nivel' => 1, 'nombre_cuenta' => 'Activos intangibles'],
            ['codigo_agrupador' => '176.01', 'nivel' => 2, 'nombre_cuenta' => 'Activos intangibles'],
            ['codigo_agrupador' => '177', 'nivel' => 1, 'nombre_cuenta' => 'Gastos de organización'],
            ['codigo_agrupador' => '177.01', 'nivel' => 2, 'nombre_cuenta' => 'Gastos de organización'],
            ['codigo_agrupador' => '178', 'nivel' => 1, 'nombre_cuenta' => 'Investigación y desarrollo de mercado'],
            ['codigo_agrupador' => '178.01', 'nivel' => 2, 'nombre_cuenta' => 'Investigación y desarrollo de mercado'],
            ['codigo_agrupador' => '179', 'nivel' => 1, 'nombre_cuenta' => 'Marcas y patentes'],
            ['codigo_agrupador' => '179.01', 'nivel' => 2, 'nombre_cuenta' => 'Marcas y patentes'],
            ['codigo_agrupador' => '180', 'nivel' => 1, 'nombre_cuenta' => 'Crédito mercantil'],
            ['codigo_agrupador' => '180.01', 'nivel' => 2, 'nombre_cuenta' => 'Crédito mercantil'],
            ['codigo_agrupador' => '181', 'nivel' => 1, 'nombre_cuenta' => 'Gastos de instalación'],
            ['codigo_agrupador' => '181.01', 'nivel' => 2, 'nombre_cuenta' => 'Gastos de instalación'],
            ['codigo_agrupador' => '182', 'nivel' => 1, 'nombre_cuenta' => 'Otros activos diferidos'],
            ['codigo_agrupador' => '182.01', 'nivel' => 2, 'nombre_cuenta' => 'Otros activos diferidos'],
            ['codigo_agrupador' => '183', 'nivel' => 1, 'nombre_cuenta' => 'Amortización acumulada de activos diferidos'],
            ['codigo_agrupador' => '183.01', 'nivel' => 2, 'nombre_cuenta' => 'Amortización acumulada de gastos diferidos'],
            ['codigo_agrupador' => '183.02', 'nivel' => 2, 'nombre_cuenta' => 'Amortización acumulada de gastos pre operativos'],
            ['codigo_agrupador' => '183.03', 'nivel' => 2, 'nombre_cuenta' => 'Amortización acumulada de regalías, asistencia técnica y otros gastos diferidos'],
            ['codigo_agrupador' => '183.04', 'nivel' => 2, 'nombre_cuenta' => 'Amortización acumulada de activos intangibles'],
            ['codigo_agrupador' => '183.05', 'nivel' => 2, 'nombre_cuenta' => 'Amortización acumulada de gastos de organización'],
            ['codigo_agrupador' => '183.06', 'nivel' => 2, 'nombre_cuenta' => 'Amortización acumulada de investigación y desarrollo de mercado'],
            ['codigo_agrupador' => '183.07', 'nivel' => 2, 'nombre_cuenta' => 'Amortización acumulada de marcas y patentes'],
            ['codigo_agrupador' => '183.08', 'nivel' => 2, 'nombre_cuenta' => 'Amortización acumulada de crédito mercantil'],
            ['codigo_agrupador' => '183.09', 'nivel' => 2, 'nombre_cuenta' => 'Amortización acumulada de gastos de instalación'],
            ['codigo_agrupador' => '183.10', 'nivel' => 2, 'nombre_cuenta' => 'Amortización acumulada de otros activos diferidos'],
            ['codigo_agrupador' => '184', 'nivel' => 1, 'nombre_cuenta' => 'Depósitos en garantía'],
            ['codigo_agrupador' => '184.01', 'nivel' => 2, 'nombre_cuenta' => 'Depósitos de fianzas'],
            ['codigo_agrupador' => '184.02', 'nivel' => 2, 'nombre_cuenta' => 'Depósitos de arrendamiento de bienes inmuebles'],
            ['codigo_agrupador' => '184.03', 'nivel' => 2, 'nombre_cuenta' => 'Otros depósitos en garantía'],
            ['codigo_agrupador' => '185', 'nivel' => 1, 'nombre_cuenta' => 'Impuestos diferidos'],
            ['codigo_agrupador' => '185.01', 'nivel' => 2, 'nombre_cuenta' => 'Impuestos diferidos ISR'],
            ['codigo_agrupador' => '186', 'nivel' => 1, 'nombre_cuenta' => 'Cuentas y documentos por cobrar a largo plazo'],
            ['codigo_agrupador' => '186.01', 'nivel' => 2, 'nombre_cuenta' => 'Cuentas y documentos por cobrar a largo plazo nacional'],
            ['codigo_agrupador' => '186.02', 'nivel' => 2, 'nombre_cuenta' => 'Cuentas y documentos por cobrar a largo plazo extranjero'],
            ['codigo_agrupador' => '186.03', 'nivel' => 2, 'nombre_cuenta' => 'Cuentas y documentos por cobrar a largo plazo nacional parte relacionada'],
            ['codigo_agrupador' => '186.04', 'nivel' => 2, 'nombre_cuenta' => 'Cuentas y documentos por cobrar a largo plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '186.05', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por cobrar a largo plazo nacional'],
            ['codigo_agrupador' => '186.06', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por cobrar a largo plazo extranjero'],
            ['codigo_agrupador' => '186.07', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por cobrar a largo plazo nacional parte relacionada'],
            ['codigo_agrupador' => '186.08', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por cobrar a largo plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '186.09', 'nivel' => 2, 'nombre_cuenta' => 'Otras cuentas y documentos por cobrar a largo plazo'],
            ['codigo_agrupador' => '186.10', 'nivel' => 2, 'nombre_cuenta' => 'Otras cuentas y documentos por cobrar a largo plazo parte relacionada'],
            ['codigo_agrupador' => '187', 'nivel' => 1, 'nombre_cuenta' => 'Participación de los trabajadores en las utilidades diferidas'],
            ['codigo_agrupador' => '187.01', 'nivel' => 2, 'nombre_cuenta' => 'Participación de los trabajadores en las utilidades diferidas'],
            ['codigo_agrupador' => '188', 'nivel' => 1, 'nombre_cuenta' => 'Inversiones permanentes en acciones'],
            ['codigo_agrupador' => '188.01', 'nivel' => 2, 'nombre_cuenta' => 'Inversiones a largo plazo en subsidiarias'],
            ['codigo_agrupador' => '188.02', 'nivel' => 2, 'nombre_cuenta' => 'Inversiones a largo plazo en asociadas'],
            ['codigo_agrupador' => '188.03', 'nivel' => 2, 'nombre_cuenta' => 'Otras inversiones permanentes en acciones'],
            ['codigo_agrupador' => '189', 'nivel' => 1, 'nombre_cuenta' => 'Estimación por deterioro de inversiones permanentes en acciones'],
            ['codigo_agrupador' => '189.01', 'nivel' => 2, 'nombre_cuenta' => 'Estimación por deterioro de inversiones permanentes en acciones'],
            ['codigo_agrupador' => '190', 'nivel' => 1, 'nombre_cuenta' => 'Otros instrumentos financieros'],
            ['codigo_agrupador' => '190.01', 'nivel' => 2, 'nombre_cuenta' => 'Otros instrumentos financieros'],
            ['codigo_agrupador' => '191', 'nivel' => 1, 'nombre_cuenta' => 'Otros activos a largo plazo'],
            ['codigo_agrupador' => '191.01', 'nivel' => 2, 'nombre_cuenta' => 'Otros activos a largo plazo'],

            // ==================== PASIVO (200) ====================
            ['codigo_agrupador' => '200', 'nivel' => 1, 'nombre_cuenta' => 'Pasivo'],
            ['codigo_agrupador' => '200.01', 'nivel' => 1, 'nombre_cuenta' => 'Pasivo a corto plazo'],
            ['codigo_agrupador' => '201', 'nivel' => 1, 'nombre_cuenta' => 'Proveedores'],
            ['codigo_agrupador' => '201.01', 'nivel' => 2, 'nombre_cuenta' => 'Proveedores nacionales'],
            ['codigo_agrupador' => '201.02', 'nivel' => 2, 'nombre_cuenta' => 'Proveedores extranjeros'],
            ['codigo_agrupador' => '201.03', 'nivel' => 2, 'nombre_cuenta' => 'Proveedores nacionales parte relacionada'],
            ['codigo_agrupador' => '201.04', 'nivel' => 2, 'nombre_cuenta' => 'Proveedores extranjeros parte relacionada'],
            ['codigo_agrupador' => '202', 'nivel' => 1, 'nombre_cuenta' => 'Cuentas por pagar a corto plazo'],
            ['codigo_agrupador' => '202.01', 'nivel' => 2, 'nombre_cuenta' => 'Documentos por pagar bancario y financiero nacional'],
            ['codigo_agrupador' => '202.02', 'nivel' => 2, 'nombre_cuenta' => 'Documentos por pagar bancario y financiero extranjero'],
            ['codigo_agrupador' => '202.03', 'nivel' => 2, 'nombre_cuenta' => 'Documentos y cuentas por pagar a corto plazo nacional'],
            ['codigo_agrupador' => '202.04', 'nivel' => 2, 'nombre_cuenta' => 'Documentos y cuentas por pagar a corto plazo extranjero'],
            ['codigo_agrupador' => '202.05', 'nivel' => 2, 'nombre_cuenta' => 'Documentos y cuentas por pagar a corto plazo nacional parte relacionada'],
            ['codigo_agrupador' => '202.06', 'nivel' => 2, 'nombre_cuenta' => 'Documentos y cuentas por pagar a corto plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '202.07', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por pagar a corto plazo nacional'],
            ['codigo_agrupador' => '202.08', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por pagar a corto plazo extranjero'],
            ['codigo_agrupador' => '202.09', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por pagar a corto plazo nacional parte relacionada'],
            ['codigo_agrupador' => '202.10', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por pagar a corto plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '202.11', 'nivel' => 2, 'nombre_cuenta' => 'Dividendo por pagar nacional'],
            ['codigo_agrupador' => '202.12', 'nivel' => 2, 'nombre_cuenta' => 'Dividendo por pagar extranjero'],
            ['codigo_agrupador' => '203', 'nivel' => 1, 'nombre_cuenta' => 'Cobros anticipados a corto plazo'],
            ['codigo_agrupador' => '203.01', 'nivel' => 2, 'nombre_cuenta' => 'Rentas cobradas por anticipado a corto plazo nacional'],
            ['codigo_agrupador' => '203.02', 'nivel' => 2, 'nombre_cuenta' => 'Rentas cobradas por anticipado a corto plazo extranjero'],
            ['codigo_agrupador' => '203.03', 'nivel' => 2, 'nombre_cuenta' => 'Rentas cobradas por anticipado a corto plazo nacional parte relacionada'],
            ['codigo_agrupador' => '203.04', 'nivel' => 2, 'nombre_cuenta' => 'Rentas cobradas por anticipado a corto plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '203.05', 'nivel' => 2, 'nombre_cuenta' => 'Intereses cobrados por anticipado a corto plazo nacional'],
            ['codigo_agrupador' => '203.06', 'nivel' => 2, 'nombre_cuenta' => 'Intereses cobrados por anticipado a corto plazo extranjero'],
            ['codigo_agrupador' => '203.07', 'nivel' => 2, 'nombre_cuenta' => 'Intereses cobrados por anticipado a corto plazo nacional parte relacionada'],
            ['codigo_agrupador' => '203.08', 'nivel' => 2, 'nombre_cuenta' => 'Intereses cobrados por anticipado a corto plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '203.09', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero cobrados por anticipado a corto plazo nacional'],
            ['codigo_agrupador' => '203.10', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero cobrados por anticipado a corto plazo extranjero'],
            ['codigo_agrupador' => '203.11', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero cobrados por anticipado a corto plazo nacional parte relacionada'],
            ['codigo_agrupador' => '203.12', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero cobrados por anticipado a corto plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '203.13', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero cobrados por anticipado a corto plazo nacional'],
            ['codigo_agrupador' => '203.14', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero cobrados por anticipado a corto plazo extranjero'],
            ['codigo_agrupador' => '203.15', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero cobrados por anticipado a corto plazo nacional parte relacionada'],
            ['codigo_agrupador' => '203.16', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero cobrados por anticipado a corto plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '203.17', 'nivel' => 2, 'nombre_cuenta' => 'Derechos fiduciarios'],
            ['codigo_agrupador' => '203.18', 'nivel' => 2, 'nombre_cuenta' => 'Otros cobros anticipados'],
            ['codigo_agrupador' => '204', 'nivel' => 1, 'nombre_cuenta' => 'Instrumentos financieros a corto plazo'],
            ['codigo_agrupador' => '204.01', 'nivel' => 2, 'nombre_cuenta' => 'Instrumentos financieros a corto plazo'],
            ['codigo_agrupador' => '205', 'nivel' => 1, 'nombre_cuenta' => 'Acreedores diversos a corto plazo'],
            ['codigo_agrupador' => '205.01', 'nivel' => 2, 'nombre_cuenta' => 'Socios, accionistas o representante legal'],
            ['codigo_agrupador' => '205.02', 'nivel' => 2, 'nombre_cuenta' => 'Acreedores diversos a corto plazo nacional'],
            ['codigo_agrupador' => '205.03', 'nivel' => 2, 'nombre_cuenta' => 'Acreedores diversos a corto plazo extranjero'],
            ['codigo_agrupador' => '205.04', 'nivel' => 2, 'nombre_cuenta' => 'Acreedores diversos a corto plazo nacional parte relacionada'],
            ['codigo_agrupador' => '205.05', 'nivel' => 2, 'nombre_cuenta' => 'Acreedores diversos a corto plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '205.06', 'nivel' => 2, 'nombre_cuenta' => 'Otros acreedores diversos a corto plazo'],
            ['codigo_agrupador' => '206', 'nivel' => 1, 'nombre_cuenta' => 'Anticipo de cliente'],
            ['codigo_agrupador' => '206.01', 'nivel' => 2, 'nombre_cuenta' => 'Anticipo de cliente nacional'],
            ['codigo_agrupador' => '206.02', 'nivel' => 2, 'nombre_cuenta' => 'Anticipo de cliente extranjero'],
            ['codigo_agrupador' => '206.03', 'nivel' => 2, 'nombre_cuenta' => 'Anticipo de cliente nacional parte relacionada'],
            ['codigo_agrupador' => '206.04', 'nivel' => 2, 'nombre_cuenta' => 'Anticipo de cliente extranjero parte relacionada'],
            ['codigo_agrupador' => '206.05', 'nivel' => 2, 'nombre_cuenta' => 'Otros anticipos de clientes'],
            ['codigo_agrupador' => '207', 'nivel' => 1, 'nombre_cuenta' => 'Impuestos trasladados'],
            ['codigo_agrupador' => '207.01', 'nivel' => 2, 'nombre_cuenta' => 'IVA trasladado'],
            ['codigo_agrupador' => '207.02', 'nivel' => 2, 'nombre_cuenta' => 'IEPS trasladado'],
            ['codigo_agrupador' => '208', 'nivel' => 1, 'nombre_cuenta' => 'Impuestos trasladados cobrados'],
            ['codigo_agrupador' => '208.01', 'nivel' => 2, 'nombre_cuenta' => 'IVA trasladado cobrado'],
            ['codigo_agrupador' => '208.02', 'nivel' => 2, 'nombre_cuenta' => 'IEPS trasladado cobrado'],
            ['codigo_agrupador' => '209', 'nivel' => 1, 'nombre_cuenta' => 'Impuestos trasladados no cobrados'],
            ['codigo_agrupador' => '209.01', 'nivel' => 2, 'nombre_cuenta' => 'IVA trasladado no cobrado'],
            ['codigo_agrupador' => '209.02', 'nivel' => 2, 'nombre_cuenta' => 'IEPS trasladado no cobrado'],
            ['codigo_agrupador' => '210', 'nivel' => 1, 'nombre_cuenta' => 'Provisión de sueldos y salarios por pagar'],
            ['codigo_agrupador' => '210.01', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de sueldos y salarios por pagar'],
            ['codigo_agrupador' => '210.02', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de vacaciones por pagar'],
            ['codigo_agrupador' => '210.03', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de aguinaldo por pagar'],
            ['codigo_agrupador' => '210.04', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de fondo de ahorro por pagar'],
            ['codigo_agrupador' => '210.05', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de asimilados a salarios por pagar'],
            ['codigo_agrupador' => '210.06', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de anticipos o remanentes por distribuir'],
            ['codigo_agrupador' => '210.07', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de otros sueldos y salarios por pagar'],
            ['codigo_agrupador' => '211', 'nivel' => 1, 'nombre_cuenta' => 'Provisión de contribuciones de seguridad social por pagar'],
            ['codigo_agrupador' => '211.01', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de IMSS patronal por pagar'],
            ['codigo_agrupador' => '211.02', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de SAR por pagar'],
            ['codigo_agrupador' => '211.03', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de infonavit por pagar'],
            ['codigo_agrupador' => '212', 'nivel' => 1, 'nombre_cuenta' => 'Provisión de impuesto estatal sobre nómina por pagar'],
            ['codigo_agrupador' => '212.01', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de impuesto estatal sobre nómina por pagar'],
            ['codigo_agrupador' => '213', 'nivel' => 1, 'nombre_cuenta' => 'Impuestos y derechos por pagar'],
            ['codigo_agrupador' => '213.01', 'nivel' => 2, 'nombre_cuenta' => 'IVA por pagar'],
            ['codigo_agrupador' => '213.02', 'nivel' => 2, 'nombre_cuenta' => 'IEPS por pagar'],
            ['codigo_agrupador' => '213.03', 'nivel' => 2, 'nombre_cuenta' => 'ISR por pagar'],
            ['codigo_agrupador' => '213.04', 'nivel' => 2, 'nombre_cuenta' => 'Impuesto estatal sobre nómina por pagar'],
            ['codigo_agrupador' => '213.05', 'nivel' => 2, 'nombre_cuenta' => 'Impuesto estatal y municipal por pagar'],
            ['codigo_agrupador' => '213.06', 'nivel' => 2, 'nombre_cuenta' => 'Derechos por pagar'],
            ['codigo_agrupador' => '213.07', 'nivel' => 2, 'nombre_cuenta' => 'Otros impuestos por pagar'],
            ['codigo_agrupador' => '214', 'nivel' => 1, 'nombre_cuenta' => 'Dividendos por pagar'],
            ['codigo_agrupador' => '214.01', 'nivel' => 2, 'nombre_cuenta' => 'Dividendos por pagar'],
            ['codigo_agrupador' => '215', 'nivel' => 1, 'nombre_cuenta' => 'PTU por pagar'],
            ['codigo_agrupador' => '215.01', 'nivel' => 2, 'nombre_cuenta' => 'PTU por pagar'],
            ['codigo_agrupador' => '215.02', 'nivel' => 2, 'nombre_cuenta' => 'PTU por pagar de ejercicios anteriores'],
            ['codigo_agrupador' => '215.03', 'nivel' => 2, 'nombre_cuenta' => 'Provisión de PTU por pagar'],
            ['codigo_agrupador' => '216', 'nivel' => 1, 'nombre_cuenta' => 'Impuestos retenidos'],
            ['codigo_agrupador' => '216.01', 'nivel' => 2, 'nombre_cuenta' => 'Impuestos retenidos de ISR por sueldos y salarios'],
            ['codigo_agrupador' => '216.02', 'nivel' => 2, 'nombre_cuenta' => 'Impuestos retenidos de ISR por asimilados a salarios'],
            ['codigo_agrupador' => '216.03', 'nivel' => 2, 'nombre_cuenta' => 'Impuestos retenidos de ISR por arrendamiento'],
            ['codigo_agrupador' => '216.04', 'nivel' => 2, 'nombre_cuenta' => 'Impuestos retenidos de ISR por servicios profesionales'],
            ['codigo_agrupador' => '216.05', 'nivel' => 2, 'nombre_cuenta' => 'Impuestos retenidos de ISR por dividendos'],
            ['codigo_agrupador' => '216.06', 'nivel' => 2, 'nombre_cuenta' => 'Impuestos retenidos de ISR por intereses'],
            ['codigo_agrupador' => '216.07', 'nivel' => 2, 'nombre_cuenta' => 'Impuestos retenidos de ISR por pagos al extranjero'],
            ['codigo_agrupador' => '216.08', 'nivel' => 2, 'nombre_cuenta' => 'Impuestos retenidos de ISR por venta de acciones'],
            ['codigo_agrupador' => '216.09', 'nivel' => 2, 'nombre_cuenta' => 'Impuestos retenidos de ISR por venta de partes sociales'],
            ['codigo_agrupador' => '216.10', 'nivel' => 2, 'nombre_cuenta' => 'Impuestos retenidos de IVA'],
            ['codigo_agrupador' => '216.11', 'nivel' => 2, 'nombre_cuenta' => 'Retenciones de IMSS a los trabajadores'],
            ['codigo_agrupador' => '216.12', 'nivel' => 2, 'nombre_cuenta' => 'Otras impuestos retenidos'],
            ['codigo_agrupador' => '217', 'nivel' => 1, 'nombre_cuenta' => 'Pagos realizados por cuenta de terceros'],
            ['codigo_agrupador' => '217.01', 'nivel' => 2, 'nombre_cuenta' => 'Pagos realizados por cuenta de terceros'],
            ['codigo_agrupador' => '218', 'nivel' => 1, 'nombre_cuenta' => 'Otros pasivos a corto plazo'],
            ['codigo_agrupador' => '218.01', 'nivel' => 2, 'nombre_cuenta' => 'Otros pasivos a corto plazo'],
            ['codigo_agrupador' => '200.02', 'nivel' => 1, 'nombre_cuenta' => 'Pasivo a largo plazo'],
            ['codigo_agrupador' => '251', 'nivel' => 1, 'nombre_cuenta' => 'Acreedores diversos a largo plazo'],
            ['codigo_agrupador' => '251.01', 'nivel' => 2, 'nombre_cuenta' => 'Socios, accionistas o representante legal'],
            ['codigo_agrupador' => '251.02', 'nivel' => 2, 'nombre_cuenta' => 'Acreedores diversos a largo plazo nacional'],
            ['codigo_agrupador' => '251.03', 'nivel' => 2, 'nombre_cuenta' => 'Acreedores diversos a largo plazo extranjero'],
            ['codigo_agrupador' => '251.04', 'nivel' => 2, 'nombre_cuenta' => 'Acreedores diversos a largo plazo nacional parte relacionada'],
            ['codigo_agrupador' => '251.05', 'nivel' => 2, 'nombre_cuenta' => 'Acreedores diversos a largo plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '251.06', 'nivel' => 2, 'nombre_cuenta' => 'Otros acreedores diversos a largo plazo'],
            ['codigo_agrupador' => '252', 'nivel' => 1, 'nombre_cuenta' => 'Cuentas por pagar a largo plazo'],
            ['codigo_agrupador' => '252.01', 'nivel' => 2, 'nombre_cuenta' => 'Documentos bancarios y financieros por pagar a largo plazo nacional'],
            ['codigo_agrupador' => '252.02', 'nivel' => 2, 'nombre_cuenta' => 'Documentos bancarios y financieros por pagar a largo plazo extranjero'],
            ['codigo_agrupador' => '252.03', 'nivel' => 2, 'nombre_cuenta' => 'Documentos y cuentas por pagar a largo plazo nacional'],
            ['codigo_agrupador' => '252.04', 'nivel' => 2, 'nombre_cuenta' => 'Documentos y cuentas por pagar a largo plazo extranjero'],
            ['codigo_agrupador' => '252.05', 'nivel' => 2, 'nombre_cuenta' => 'Documentos y cuentas por pagar a largo plazo nacional parte relacionada'],
            ['codigo_agrupador' => '252.06', 'nivel' => 2, 'nombre_cuenta' => 'Documentos y cuentas por pagar a largo plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '252.07', 'nivel' => 2, 'nombre_cuenta' => 'Hipotecas por pagar a largo plazo nacional'],
            ['codigo_agrupador' => '252.08', 'nivel' => 2, 'nombre_cuenta' => 'Hipotecas por pagar a largo plazo extranjero'],
            ['codigo_agrupador' => '252.09', 'nivel' => 2, 'nombre_cuenta' => 'Hipotecas por pagar a largo plazo nacional parte relacionada'],
            ['codigo_agrupador' => '252.10', 'nivel' => 2, 'nombre_cuenta' => 'Hipotecas por pagar a largo plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '252.11', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por pagar a largo plazo nacional'],
            ['codigo_agrupador' => '252.12', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por pagar a largo plazo extranjero'],
            ['codigo_agrupador' => '252.13', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por pagar a largo plazo nacional parte relacionada'],
            ['codigo_agrupador' => '252.14', 'nivel' => 2, 'nombre_cuenta' => 'Intereses por pagar a largo plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '252.15', 'nivel' => 2, 'nombre_cuenta' => 'Dividendos por pagar nacionales'],
            ['codigo_agrupador' => '252.16', 'nivel' => 2, 'nombre_cuenta' => 'Dividendos por pagar extranjeros'],
            ['codigo_agrupador' => '252.17', 'nivel' => 2, 'nombre_cuenta' => 'Otras cuentas y documentos por pagar a largo plazo'],
            ['codigo_agrupador' => '253', 'nivel' => 1, 'nombre_cuenta' => 'Cobros anticipados a largo plazo'],
            ['codigo_agrupador' => '253.01', 'nivel' => 2, 'nombre_cuenta' => 'Rentas cobradas por anticipado a largo plazo nacional'],
            ['codigo_agrupador' => '253.02', 'nivel' => 2, 'nombre_cuenta' => 'Rentas cobradas por anticipado a largo plazo extranjero'],
            ['codigo_agrupador' => '253.03', 'nivel' => 2, 'nombre_cuenta' => 'Rentas cobradas por anticipado a largo plazo nacional parte relacionada'],
            ['codigo_agrupador' => '253.04', 'nivel' => 2, 'nombre_cuenta' => 'Rentas cobradas por anticipado a largo plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '253.05', 'nivel' => 2, 'nombre_cuenta' => 'Intereses cobrados por anticipado a largo plazo nacional'],
            ['codigo_agrupador' => '253.06', 'nivel' => 2, 'nombre_cuenta' => 'Intereses cobrados por anticipado a largo plazo extranjero'],
            ['codigo_agrupador' => '253.07', 'nivel' => 2, 'nombre_cuenta' => 'Intereses cobrados por anticipado a largo plazo nacional parte relacionada'],
            ['codigo_agrupador' => '253.08', 'nivel' => 2, 'nombre_cuenta' => 'Intereses cobrados por anticipado a largo plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '253.09', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero cobrados por anticipado a largo plazo nacional'],
            ['codigo_agrupador' => '253.10', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero cobrados por anticipado a largo plazo extranjero'],
            ['codigo_agrupador' => '253.11', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero cobrados por anticipado a largo plazo nacional parte relacionada'],
            ['codigo_agrupador' => '253.12', 'nivel' => 2, 'nombre_cuenta' => 'Factoraje financiero cobrados por anticipado a largo plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '253.13', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero cobrados por anticipado a largo plazo nacional'],
            ['codigo_agrupador' => '253.14', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero cobrados por anticipado a largo plazo extranjero'],
            ['codigo_agrupador' => '253.15', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero cobrados por anticipado a largo plazo nacional parte relacionada'],
            ['codigo_agrupador' => '253.16', 'nivel' => 2, 'nombre_cuenta' => 'Arrendamiento financiero cobrados por anticipado a largo plazo extranjero parte relacionada'],
            ['codigo_agrupador' => '253.17', 'nivel' => 2, 'nombre_cuenta' => 'Derechos fiduciarios'],
            ['codigo_agrupador' => '253.18', 'nivel' => 2, 'nombre_cuenta' => 'Otros cobros anticipados'],
            ['codigo_agrupador' => '254', 'nivel' => 1, 'nombre_cuenta' => 'Instrumentos financieros a largo plazo'],
            ['codigo_agrupador' => '254.01', 'nivel' => 2, 'nombre_cuenta' => 'Instrumentos financieros a largo plazo'],
            ['codigo_agrupador' => '255', 'nivel' => 1, 'nombre_cuenta' => 'Pasivos por beneficios a los empleados a largo plazo'],
            ['codigo_agrupador' => '255.01', 'nivel' => 2, 'nombre_cuenta' => 'Pasivos por beneficios a los empleados a largo plazo'],
            ['codigo_agrupador' => '256', 'nivel' => 1, 'nombre_cuenta' => 'Otros pasivos a largo plazo'],
            ['codigo_agrupador' => '256.01', 'nivel' => 2, 'nombre_cuenta' => 'Otros pasivos a largo plazo'],
            ['codigo_agrupador' => '257', 'nivel' => 1, 'nombre_cuenta' => 'Participación de los trabajadores en las utilidades diferida'],
            ['codigo_agrupador' => '257.01', 'nivel' => 2, 'nombre_cuenta' => 'Participación de los trabajadores en las utilidades diferida'],
            ['codigo_agrupador' => '258', 'nivel' => 1, 'nombre_cuenta' => 'Obligaciones contraídas de fideicomisos'],
            ['codigo_agrupador' => '258.01', 'nivel' => 2, 'nombre_cuenta' => 'Obligaciones contraídas de fideicomisos'],
            ['codigo_agrupador' => '259', 'nivel' => 1, 'nombre_cuenta' => 'Impuestos diferidos'],
            ['codigo_agrupador' => '259.01', 'nivel' => 2, 'nombre_cuenta' => 'ISR diferido'],
            ['codigo_agrupador' => '259.02', 'nivel' => 2, 'nombre_cuenta' => 'ISR por dividendo diferido'],
            ['codigo_agrupador' => '259.03', 'nivel' => 2, 'nombre_cuenta' => 'Otros impuestos diferidos'],
            ['codigo_agrupador' => '260', 'nivel' => 1, 'nombre_cuenta' => 'Pasivos diferidos'],
            ['codigo_agrupador' => '260.01', 'nivel' => 2, 'nombre_cuenta' => 'Pasivos diferidos'],

            // ==================== CAPITAL CONTABLE (300) ====================
            ['codigo_agrupador' => '300', 'nivel' => 1, 'nombre_cuenta' => 'Capital contable'],
            ['codigo_agrupador' => '301', 'nivel' => 1, 'nombre_cuenta' => 'Capital social'],
            ['codigo_agrupador' => '301.01', 'nivel' => 2, 'nombre_cuenta' => 'Capital fijo'],
            ['codigo_agrupador' => '301.02', 'nivel' => 2, 'nombre_cuenta' => 'Capital variable'],
            ['codigo_agrupador' => '301.03', 'nivel' => 2, 'nombre_cuenta' => 'Aportaciones para futuros aumentos de capital'],
            ['codigo_agrupador' => '301.04', 'nivel' => 2, 'nombre_cuenta' => 'Prima en suscripción de acciones'],
            ['codigo_agrupador' => '301.05', 'nivel' => 2, 'nombre_cuenta' => 'Prima en suscripción de partes sociales'],
            ['codigo_agrupador' => '302', 'nivel' => 1, 'nombre_cuenta' => 'Patrimonio'],
            ['codigo_agrupador' => '302.01', 'nivel' => 2, 'nombre_cuenta' => 'Patrimonio'],
            ['codigo_agrupador' => '302.02', 'nivel' => 2, 'nombre_cuenta' => 'Aportación patrimonial'],
            ['codigo_agrupador' => '302.03', 'nivel' => 2, 'nombre_cuenta' => 'Déficit o remanente del ejercicio'],
            ['codigo_agrupador' => '303', 'nivel' => 1, 'nombre_cuenta' => 'Reserva legal'],
            ['codigo_agrupador' => '303.01', 'nivel' => 2, 'nombre_cuenta' => 'Reserva legal'],
            ['codigo_agrupador' => '304', 'nivel' => 1, 'nombre_cuenta' => 'Resultado de ejercicios anteriores'],
            ['codigo_agrupador' => '304.01', 'nivel' => 2, 'nombre_cuenta' => 'Utilidad de ejercicios anteriores'],
            ['codigo_agrupador' => '304.02', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida de ejercicios anteriores'],
            ['codigo_agrupador' => '304.03', 'nivel' => 2, 'nombre_cuenta' => 'Resultado integral de ejercicios anteriores'],
            ['codigo_agrupador' => '304.04', 'nivel' => 2, 'nombre_cuenta' => 'Déficit o remanente de ejercicio anteriores'],
            ['codigo_agrupador' => '305', 'nivel' => 1, 'nombre_cuenta' => 'Resultado del ejercicio'],
            ['codigo_agrupador' => '305.01', 'nivel' => 2, 'nombre_cuenta' => 'Utilidad del ejercicio'],
            ['codigo_agrupador' => '305.02', 'nivel' => 2, 'nombre_cuenta' => 'Pérdida del ejercicio'],
            ['codigo_agrupador' => '305.03', 'nivel' => 2, 'nombre_cuenta' => 'Resultado integral'],
            ['codigo_agrupador' => '306', 'nivel' => 1, 'nombre_cuenta' => 'Otras cuentas de capital'],
            ['codigo_agrupador' => '306.01', 'nivel' => 2, 'nombre_cuenta' => 'Otras cuentas de capital'],

            // ==================== INGRESOS (400) ====================
            ['codigo_agrupador' => '400', 'nivel' => 1, 'nombre_cuenta' => 'Ingresos'],
            ['codigo_agrupador' => '401', 'nivel' => 1, 'nombre_cuenta' => 'Ingresos'],
            ['codigo_agrupador' => '401.01', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios gravados a la tasa general'],
            ['codigo_agrupador' => '401.02', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios gravados a la tasa general de contado'],
            ['codigo_agrupador' => '401.03', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios gravados a la tasa general a crédito'],
            ['codigo_agrupador' => '401.04', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios gravados al 0%'],
            ['codigo_agrupador' => '401.05', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios gravados al 0% de contado'],
            ['codigo_agrupador' => '401.06', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios gravados al 0% a crédito'],
            ['codigo_agrupador' => '401.07', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios exentos'],
            ['codigo_agrupador' => '401.08', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios exentos de contado'],
            ['codigo_agrupador' => '401.09', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios exentos a crédito'],
            ['codigo_agrupador' => '401.10', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios gravados a la tasa general nacionales partes relacionadas'],
            ['codigo_agrupador' => '401.11', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios gravados a la tasa general extranjeros partes relacionadas'],
            ['codigo_agrupador' => '401.12', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios gravados al 0% nacionales partes relacionadas'],
            ['codigo_agrupador' => '401.13', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios gravados al 0% extranjeros partes relacionadas'],
            ['codigo_agrupador' => '401.14', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios exentos nacionales partes relacionadas'],
            ['codigo_agrupador' => '401.15', 'nivel' => 2, 'nombre_cuenta' => 'Ventas y/o servicios exentos extranjeros partes relacionadas'],
            ['codigo_agrupador' => '401.16', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por servicios administrativos'],
            ['codigo_agrupador' => '401.17', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por servicios administrativos nacionales partes relacionadas'],
            ['codigo_agrupador' => '401.18', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por servicios administrativos extranjeros partes relacionadas'],
            ['codigo_agrupador' => '401.19', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por servicios profesionales'],
            ['codigo_agrupador' => '401.20', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por servicios profesionales nacionales partes relacionadas'],
            ['codigo_agrupador' => '401.21', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por servicios profesionales extranjeros partes relacionadas'],
            ['codigo_agrupador' => '401.22', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por arrendamiento'],
            ['codigo_agrupador' => '401.23', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por arrendamiento nacionales partes relacionadas'],
            ['codigo_agrupador' => '401.24', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por arrendamiento extranjeros partes relacionadas'],
            ['codigo_agrupador' => '401.25', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por exportación'],
            ['codigo_agrupador' => '401.26', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por comisiones'],
            ['codigo_agrupador' => '401.27', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por maquila'],
            ['codigo_agrupador' => '401.28', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por coordinados'],
            ['codigo_agrupador' => '401.29', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por regalías'],
            ['codigo_agrupador' => '401.30', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por asistencia técnica'],
            ['codigo_agrupador' => '401.31', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por donativos'],
            ['codigo_agrupador' => '401.32', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por intereses (actividad propia)'],
            ['codigo_agrupador' => '401.33', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos de copropiedad'],
            ['codigo_agrupador' => '401.34', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por fideicomisos'],
            ['codigo_agrupador' => '401.35', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por factoraje financiero'],
            ['codigo_agrupador' => '401.36', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por arrendamiento financiero'],
            ['codigo_agrupador' => '401.37', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos de extranjeros con establecimiento en el país'],
            ['codigo_agrupador' => '401.38', 'nivel' => 2, 'nombre_cuenta' => 'Otros ingresos propios'],
            ['codigo_agrupador' => '402', 'nivel' => 1, 'nombre_cuenta' => 'Devoluciones, descuentos o bonificaciones sobre ingresos'],
            ['codigo_agrupador' => '402.01', 'nivel' => 2, 'nombre_cuenta' => 'Devoluciones, descuentos o bonificaciones sobre ventas y/o servicios a la tasa general'],
            ['codigo_agrupador' => '402.02', 'nivel' => 2, 'nombre_cuenta' => 'Devoluciones, descuentos o bonificaciones sobre ventas y/o servicios al 0%'],
            ['codigo_agrupador' => '402.03', 'nivel' => 2, 'nombre_cuenta' => 'Devoluciones, descuentos o bonificaciones sobre ventas y/o servicios exentos'],
            ['codigo_agrupador' => '402.04', 'nivel' => 2, 'nombre_cuenta' => 'Devoluciones, descuentos o bonificaciones de otros ingresos'],
            ['codigo_agrupador' => '403', 'nivel' => 1, 'nombre_cuenta' => 'Otros ingresos'],
            ['codigo_agrupador' => '403.01', 'nivel' => 2, 'nombre_cuenta' => 'Otros Ingresos'],
            ['codigo_agrupador' => '403.02', 'nivel' => 2, 'nombre_cuenta' => 'Otros ingresos nacionales parte relacionada'],
            ['codigo_agrupador' => '403.03', 'nivel' => 2, 'nombre_cuenta' => 'Otros ingresos extranjeros parte relacionada'],
            ['codigo_agrupador' => '403.04', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por operaciones discontinuas'],
            ['codigo_agrupador' => '403.05', 'nivel' => 2, 'nombre_cuenta' => 'Ingresos por condonación de adeudo'],

            // ==================== COSTOS (500) ====================
            ['codigo_agrupador' => '500', 'nivel' => 1, 'nombre_cuenta' => 'Costos'],
            ['codigo_agrupador' => '501', 'nivel' => 1, 'nombre_cuenta' => 'Costo de venta y/o servicio'],
            ['codigo_agrupador' => '501.01', 'nivel' => 2, 'nombre_cuenta' => 'Costo de venta'],
            ['codigo_agrupador' => '501.02', 'nivel' => 2, 'nombre_cuenta' => 'Costo de servicios (Mano de obra)'],
            ['codigo_agrupador' => '501.03', 'nivel' => 2, 'nombre_cuenta' => 'Materia prima directa utilizada para la producción'],
            ['codigo_agrupador' => '501.04', 'nivel' => 2, 'nombre_cuenta' => 'Materia prima consumida en el proceso productivo'],
            ['codigo_agrupador' => '501.05', 'nivel' => 2, 'nombre_cuenta' => 'Mano de obra directa consumida'],
            ['codigo_agrupador' => '501.06', 'nivel' => 2, 'nombre_cuenta' => 'Mano de obra directa'],
            ['codigo_agrupador' => '501.07', 'nivel' => 2, 'nombre_cuenta' => 'Cargos indirectos de producción'],
            ['codigo_agrupador' => '501.08', 'nivel' => 2, 'nombre_cuenta' => 'Otros conceptos de costo'],
            ['codigo_agrupador' => '502', 'nivel' => 1, 'nombre_cuenta' => 'Compras'],
            ['codigo_agrupador' => '502.01', 'nivel' => 2, 'nombre_cuenta' => 'Compras nacionales'],
            ['codigo_agrupador' => '502.02', 'nivel' => 2, 'nombre_cuenta' => 'Compras nacionales parte relacionada'],
            ['codigo_agrupador' => '502.03', 'nivel' => 2, 'nombre_cuenta' => 'Compras de Importación'],
            ['codigo_agrupador' => '502.04', 'nivel' => 2, 'nombre_cuenta' => 'Compras de Importación partes relacionadas'],
            ['codigo_agrupador' => '503', 'nivel' => 1, 'nombre_cuenta' => 'Devoluciones, descuentos o bonificaciones sobre compras'],
            ['codigo_agrupador' => '503.01', 'nivel' => 2, 'nombre_cuenta' => 'Devoluciones, descuentos o bonificaciones sobre compras'],
            ['codigo_agrupador' => '504', 'nivel' => 1, 'nombre_cuenta' => 'Otras cuentas de costos'],
            ['codigo_agrupador' => '504.01', 'nivel' => 2, 'nombre_cuenta' => 'Gastos indirectos de fabricación'],
            ['codigo_agrupador' => '504.02', 'nivel' => 2, 'nombre_cuenta' => 'Gastos indirectos de fabricación de partes relacionadas nacionales'],
            ['codigo_agrupador' => '504.03', 'nivel' => 2, 'nombre_cuenta' => 'Gastos indirectos de fabricación de partes relacionadas extranjeras'],
            ['codigo_agrupador' => '504.04', 'nivel' => 2, 'nombre_cuenta' => 'Otras cuentas de costos incurridos'],
            ['codigo_agrupador' => '504.05', 'nivel' => 2, 'nombre_cuenta' => 'Otras cuentas de costos incurridos con partes relacionadas nacionales'],
            ['codigo_agrupador' => '504.06', 'nivel' => 2, 'nombre_cuenta' => 'Otras cuentas de costos incurridos con partes relacionadas extranjeras'],
            ['codigo_agrupador' => '504.07', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de edificios'],
            ['codigo_agrupador' => '504.08', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de maquinaria y equipo'],
            ['codigo_agrupador' => '504.09', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques'],
            ['codigo_agrupador' => '504.10', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de mobiliario y equipo de oficina'],
            ['codigo_agrupador' => '504.11', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de equipo de cómputo'],
            ['codigo_agrupador' => '504.12', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de equipo de comunicación'],
            ['codigo_agrupador' => '504.13', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de activos biológicos, vegetales y semovientes'],
            ['codigo_agrupador' => '504.14', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de otros activos fijos'],
            ['codigo_agrupador' => '504.15', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de ferrocarriles'],
            ['codigo_agrupador' => '504.16', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de embarcaciones'],
            ['codigo_agrupador' => '504.17', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de aviones'],
            ['codigo_agrupador' => '504.18', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de troqueles, moldes, matrices y herramental'],
            ['codigo_agrupador' => '504.19', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de equipo de comunicaciones telefónicas'],
            ['codigo_agrupador' => '504.20', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de equipo de comunicación satelital'],
            ['codigo_agrupador' => '504.21', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de equipo de adaptaciones para personas con capacidades diferentes'],
            ['codigo_agrupador' => '504.22', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente'],
            ['codigo_agrupador' => '504.23', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de adaptaciones y mejoras'],
            ['codigo_agrupador' => '504.24', 'nivel' => 2, 'nombre_cuenta' => 'Depreciación de otra maquinaria y equipo'],
            ['codigo_agrupador' => '504.25', 'nivel' => 2, 'nombre_cuenta' => 'Otras cuentas de costos'],
            ['codigo_agrupador' => '505', 'nivel' => 1, 'nombre_cuenta' => 'Costo de activo fijo'],
            ['codigo_agrupador' => '505.01', 'nivel' => 2, 'nombre_cuenta' => 'Costo por venta de activo fijo'],
            ['codigo_agrupador' => '505.02', 'nivel' => 2, 'nombre_cuenta' => 'Costo por baja de activo fijo'],

            // ==================== CUENTAS DE ORDEN (800) ====================
            ['codigo_agrupador' => '800', 'nivel' => 1, 'nombre_cuenta' => 'Cuentas de orden'],
            ['codigo_agrupador' => '801', 'nivel' => 1, 'nombre_cuenta' => 'UFIN del ejercicio'],
            ['codigo_agrupador' => '801.01', 'nivel' => 2, 'nombre_cuenta' => 'UFIN'],
            ['codigo_agrupador' => '801.02', 'nivel' => 2, 'nombre_cuenta' => 'Contra cuenta UFIN'],
            ['codigo_agrupador' => '802', 'nivel' => 1, 'nombre_cuenta' => 'CUFIN del ejercicio'],
            ['codigo_agrupador' => '802.01', 'nivel' => 2, 'nombre_cuenta' => 'CUFIN'],
            ['codigo_agrupador' => '802.02', 'nivel' => 2, 'nombre_cuenta' => 'Contra cuenta CUFIN'],
            ['codigo_agrupador' => '803', 'nivel' => 1, 'nombre_cuenta' => 'CUFIN de ejercicios anteriores'],
            ['codigo_agrupador' => '803.01', 'nivel' => 2, 'nombre_cuenta' => 'CUFIN de ejercicios anteriores'],
            ['codigo_agrupador' => '803.02', 'nivel' => 2, 'nombre_cuenta' => 'Contra cuenta CUFIN de ejercicios anteriores'],
            ['codigo_agrupador' => '804', 'nivel' => 1, 'nombre_cuenta' => 'CUFINRE del ejercicio'],
            ['codigo_agrupador' => '804.01', 'nivel' => 2, 'nombre_cuenta' => 'CUFINRE'],
            ['codigo_agrupador' => '804.02', 'nivel' => 2, 'nombre_cuenta' => 'Contra cuenta CUFINRE'],
            ['codigo_agrupador' => '805', 'nivel' => 1, 'nombre_cuenta' => 'CUFINRE de ejercicios anteriores'],
            ['codigo_agrupador' => '805.01', 'nivel' => 2, 'nombre_cuenta' => 'CUFINRE de ejercicios anteriores'],
            ['codigo_agrupador' => '805.02', 'nivel' => 2, 'nombre_cuenta' => 'Contra cuenta CUFINRE de ejercicios anteriores'],
            ['codigo_agrupador' => '806', 'nivel' => 1, 'nombre_cuenta' => 'CUCA del ejercicio'],
            ['codigo_agrupador' => '806.01', 'nivel' => 2, 'nombre_cuenta' => 'CUCA'],
            ['codigo_agrupador' => '806.02', 'nivel' => 2, 'nombre_cuenta' => 'Contra cuenta CUCA'],
            ['codigo_agrupador' => '807', 'nivel' => 1, 'nombre_cuenta' => 'CUCA de ejercicios anteriores'],
            ['codigo_agrupador' => '807.01', 'nivel' => 2, 'nombre_cuenta' => 'CUCA de ejercicios anteriores'],
            ['codigo_agrupador' => '807.02', 'nivel' => 2, 'nombre_cuenta' => 'Contra cuenta CUCA de ejercicios anteriores'],
            ['codigo_agrupador' => '808', 'nivel' => 1, 'nombre_cuenta' => 'Ajuste anual por inflación acumulable'],
            ['codigo_agrupador' => '808.01', 'nivel' => 2, 'nombre_cuenta' => 'Ajuste anual por inflación acumulable'],
            ['codigo_agrupador' => '808.02', 'nivel' => 2, 'nombre_cuenta' => 'Acumulación del ajuste anual inflacionario'],
            ['codigo_agrupador' => '809', 'nivel' => 1, 'nombre_cuenta' => 'Ajuste anual por inflación deducible'],
            ['codigo_agrupador' => '809.01', 'nivel' => 2, 'nombre_cuenta' => 'Ajuste anual por inflación deducible'],
            ['codigo_agrupador' => '809.02', 'nivel' => 2, 'nombre_cuenta' => 'Deducción del ajuste anual inflacionario'],
            ['codigo_agrupador' => '810', 'nivel' => 1, 'nombre_cuenta' => 'Deducción de inversión'],
            ['codigo_agrupador' => '810.01', 'nivel' => 2, 'nombre_cuenta' => 'Deducción de inversión'],
            ['codigo_agrupador' => '810.02', 'nivel' => 2, 'nombre_cuenta' => 'Contra cuenta deducción de inversiones'],
            ['codigo_agrupador' => '811', 'nivel' => 1, 'nombre_cuenta' => 'Utilidad o pérdida fiscal en venta y/o baja de activo fijo'],
            ['codigo_agrupador' => '811.01', 'nivel' => 2, 'nombre_cuenta' => 'Utilidad o pérdida fiscal en venta y/o baja de activo fijo'],
            ['codigo_agrupador' => '811.02', 'nivel' => 2, 'nombre_cuenta' => 'Contra cuenta utilidad o pérdida fiscal en venta y/o baja de activo fijo'],
            ['codigo_agrupador' => '812', 'nivel' => 1, 'nombre_cuenta' => 'Utilidad o pérdida fiscal en venta acciones o partes sociales'],
            ['codigo_agrupador' => '812.01', 'nivel' => 2, 'nombre_cuenta' => 'Utilidad o pérdida fiscal en venta acciones o partes sociales'],
            ['codigo_agrupador' => '812.02', 'nivel' => 2, 'nombre_cuenta' => 'Contra cuenta utilidad o pérdida fiscal en venta acciones o partes sociales'],
            ['codigo_agrupador' => '813', 'nivel' => 1, 'nombre_cuenta' => 'Pérdidas fiscales pendientes de amortizar actualizadas de ejercicios anteriores'],
            ['codigo_agrupador' => '813.01', 'nivel' => 2, 'nombre_cuenta' => 'Pérdidas fiscales pendientes de amortizar actualizadas de ejercicios anteriores'],
            ['codigo_agrupador' => '813.02', 'nivel' => 2, 'nombre_cuenta' => 'Actualización de pérdidas fiscales pendientes de amortizar de ejercicios anteriores'],
            ['codigo_agrupador' => '814', 'nivel' => 1, 'nombre_cuenta' => 'Mercancías recibidas en consignación'],
            ['codigo_agrupador' => '814.01', 'nivel' => 2, 'nombre_cuenta' => 'Mercancías recibidas en consignación'],
            ['codigo_agrupador' => '814.02', 'nivel' => 2, 'nombre_cuenta' => 'Consignación de mercancías recibidas'],
            ['codigo_agrupador' => '815', 'nivel' => 1, 'nombre_cuenta' => 'Crédito fiscal de IVA e IEPS por la importación de mercancías para empresas certificadas'],
            ['codigo_agrupador' => '815.01', 'nivel' => 2, 'nombre_cuenta' => 'Crédito fiscal de IVA e IEPS por la importación de mercancías'],
            ['codigo_agrupador' => '815.02', 'nivel' => 2, 'nombre_cuenta' => 'Importación de mercancías con aplicación de crédito fiscal de IVA e IEPS'],
            ['codigo_agrupador' => '816', 'nivel' => 1, 'nombre_cuenta' => 'Crédito fiscal de IVA e IEPS por la importación de activos fijos para empresas certificadas'],
            ['codigo_agrupador' => '816.01', 'nivel' => 2, 'nombre_cuenta' => 'Crédito fiscal de IVA e IEPS por la importación de activo fijo'],
            ['codigo_agrupador' => '816.02', 'nivel' => 2, 'nombre_cuenta' => 'Importación de activo fijo con aplicación de crédito fiscal de IVA e IEPS'],
            ['codigo_agrupador' => '899', 'nivel' => 1, 'nombre_cuenta' => 'Otras cuentas de orden'],
            ['codigo_agrupador' => '899.01', 'nivel' => 2, 'nombre_cuenta' => 'Otras cuentas de orden'],
            ['codigo_agrupador' => '899.02', 'nivel' => 2, 'nombre_cuenta' => 'Contra cuenta otras cuentas de orden'],
            
            // ==================== CÓDIGO ESPECIAL 000 ====================
            ['codigo_agrupador' => '000', 'nivel' => 0, 'nombre_cuenta' => 'Código para uso exclusivo de contribuyentes del sector financiero'],
        ];

        DB::table('codigos_sat')->insert($registros);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('codigos_sat');
    }
};